version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /root/monitor/alertmanager:/etc/alertmanager/
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    restart: always



  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      # - ./main.conf:/etc/nginx/nginx.conf
        - ./default.conf:/etc/nginx/conf.d/default.conf
      # -  /root/cert:/mnt  

