global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093" # alert instance ip

rule_files:
  - rules.yml   # alert rule file

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9093']
  - job_name: 'node_expoter'
    scrape_interval: 5s
    static_configs:
      - targets: ['35.85.62.243:9100'] 
